add_subdirectory(AssetsBrowser)
add_subdirectory(AudioGraphEditor)
add_subdirectory(AudioMixer)
add_subdirectory(ConsoleWindow)
add_subdirectory(GameViewport)
add_subdirectory(HierarchyWindow)
add_subdirectory(InspectorWindow)
add_subdirectory(JobQueueWindow)
add_subdirectory(MainMenuBar)
add_subdirectory(MemoryWindow)
add_subdirectory(MultithreadingWindow)
add_subdirectory(ResourcesWindow)
add_subdirectory(SceneViewport)
add_subdirectory(TextEditorWindow)