/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::AnimatorDemo*/
/*coding_end::AnimatorDemo*/

// Drives the owning GameObject's CAnimator from script, which is the whole point of
// the animation scripting API: before it, only the Inspector's Play buttons could
// trigger a transition, so no shipped game could animate anything.
//
// Keys 1/2/3 cross-fade to three named STATES of the animator's controller. Addressing
// states rather than clips is what makes a script and the graph speak about the same
// thing: a CrossFade wins for its frame and the graph resumes from the state it
// entered, so there is never a frame with two writers.
class AnimatorDemo : public IScript
{
public:

    AnimatorDemo()
    {
        /*coding_start::AnimatorDemo::AnimatorDemo*/
        /*coding_end::AnimatorDemo::AnimatorDemo*/
    }

    ~AnimatorDemo() override
    {
        /*coding_start::AnimatorDemo::~AnimatorDemo*/
        /*coding_end::AnimatorDemo::~AnimatorDemo*/
    }

    void Awake() override
    {
        /*coding_start::AnimatorDemo::Awake*/
        /*coding_end::AnimatorDemo::Awake*/
    }

    void Start() override
    {
        /*coding_start::AnimatorDemo::Start*/
        if (!Nous_Engine->Component->HasAnimator(m_ownerID))
        {
            Nous_Engine->Logger->Info("[AnimatorDemo] No CAnimator on owner %u", m_ownerID);
            return;
        }

        // The parameter surface is the PRIMARY one: a transition condition on "speed"
        // is what a player controller should be written against, with CrossFade below
        // reserved for the cases a graph edge cannot express.
        Nous_Engine->Animator->SetFloat(m_ownerID, "speed", 1.0f);
        Nous_Engine->Logger->Info("[AnimatorDemo] speed parameter reads back as %.2f",
                                  Nous_Engine->Animator->GetFloat(m_ownerID, "speed"));
        /*coding_end::AnimatorDemo::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::Update*/
        CrossFadeOnKey(NOUS_SCANCODE::Num1, m_stateA);
        CrossFadeOnKey(NOUS_SCANCODE::Num2, m_stateB);
        CrossFadeOnKey(NOUS_SCANCODE::Num3, m_stateC);

        // Once a second, so the log stays readable at 60 fps.
        m_logTimer += deltaTime;
        if (m_logTimer >= 1.0f)
        {
            m_logTimer = 0.0f;

            char state[128] = {};
            Nous_Engine->Animator->GetCurrentState(m_ownerID, state, sizeof(state));
            Nous_Engine->Logger->Info("[AnimatorDemo] state='%s' t=%.2f fading=%d",
                                      state,
                                      Nous_Engine->Animator->GetNormalizedTime(m_ownerID),
                                      Nous_Engine->Animator->IsFading(m_ownerID) ? 1 : 0);
        }
        /*coding_end::AnimatorDemo::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::AnimatorDemo::FixedUpdate*/
        /*coding_end::AnimatorDemo::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::LateUpdate*/
        /*coding_end::AnimatorDemo::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::AnimatorDemo::OnEnable*/
        /*coding_end::AnimatorDemo::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::AnimatorDemo::OnDisable*/
        /*coding_end::AnimatorDemo::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::AnimatorDemo::OnDestroy*/
        /*coding_end::AnimatorDemo::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::AnimatorDemo*/
    void CrossFadeOnKey(NOUS_SCANCODE key, const std::string& stateName)
    {
        if (stateName.empty()) return;
        if (Nous_Engine->Input->GetKey(key) != InputAPI::KeyState::DOWN) return;

        // False means the animator has no controller, or its graph has no state by
        // that name -- the most likely mistake here, and silent otherwise, so it is
        // worth logging. A state name is not a clip name: it is whatever the .nctrl
        // calls the state, which is why these are Inspector fields rather than
        // hard-coded strings.
        if (!Nous_Engine->Animator->CrossFade(m_ownerID, stateName.c_str(), m_fade))
            Nous_Engine->Logger->Info("[AnimatorDemo] no state named '%s'", stateName.c_str());
    }
    /*coding_end::AnimatorDemo*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::AnimatorDemo*/
    float m_logTimer = 0.0f;

    SCRIPT_FIELD(float, m_fade, 0.3f)

    // Defaulted to the names the demo controller uses (Task 16), so the script does
    // something the moment it is dropped on a character that has one.
    SCRIPT_FIELD(std::string, m_stateA, "Idle")
    SCRIPT_FIELD(std::string, m_stateB, "Run")
    SCRIPT_FIELD(std::string, m_stateC, "Attack")
    /*coding_end::AnimatorDemo*/
};

REGISTER_SCRIPT(AnimatorDemo)
