/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::AnimatorDemo*/
/*coding_end::AnimatorDemo*/

// Drives the owning GameObject's CAnimator from script, which is the whole point of
// the animation scripting API: before it, only the Inspector's Play buttons could
// trigger a transition, so no shipped game could animate anything.
//
// W/S drive the `speed` parameter and A/D turn the character; root motion does the
// actual travelling, along whatever direction he is facing. ThirdPersonCamera only
// watches -- the character's own script is what decides where he goes.
//
// Keys 1/2/3 cross-fade to three named STATES of the animator's controller. Addressing
// states rather than clips is what makes a script and the graph speak about the same
// thing: a CrossFade wins for its frame and the graph resumes from the state it
// entered, so there is never a frame with two writers.
class AnimatorDemo : public IScript
{
public:

    AnimatorDemo()
    {
        /*coding_start::AnimatorDemo::AnimatorDemo*/
        /*coding_end::AnimatorDemo::AnimatorDemo*/
    }

    ~AnimatorDemo() override
    {
        /*coding_start::AnimatorDemo::~AnimatorDemo*/
        /*coding_end::AnimatorDemo::~AnimatorDemo*/
    }

    void Awake() override
    {
        /*coding_start::AnimatorDemo::Awake*/
        /*coding_end::AnimatorDemo::Awake*/
    }

    void Start() override
    {
        /*coding_start::AnimatorDemo::Start*/
        if (!Nous_Engine->Component->HasAnimator(m_ownerID))
        {
            Nous_Engine->Logger->Info("[AnimatorDemo] No CAnimator on owner %u", m_ownerID);
            return;
        }

        Nous_Engine->Logger->Info("[AnimatorDemo] W/S = move, A/D = turn, Shift = sprint, "
                                  "Space = attack, F = attack (held, QA), "
                                  "1/2/3 = direct CrossFade");
        /*coding_end::AnimatorDemo::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::Update*/

        // THE PRIMARY SURFACE. A player controller says what is TRUE of the character
        // -- it is moving, it was asked to attack -- and the controller graph decides
        // what that means for playback. Nothing here names a clip or a state.
        //
        // Written every frame, not on the key edge: a transition condition is a
        // question asked continuously, so "speed" has to describe the current frame
        // rather than the last time the key changed.
        //
        // ONE SIGNED parameter rather than a second "backwards" flag. The sign is
        // what the graph already needs to distinguish the two directions, and a
        // separate bool would let the two disagree -- forward and backward both true
        // is a state the character cannot be in.
        float speed = 0.0f;
        if (IsHeld(NOUS_SCANCODE::W)) speed += 1.0f;
        if (IsHeld(NOUS_SCANCODE::S)) speed -= 1.0f;

        Nous_Engine->Animator->SetFloat(m_ownerID, "speed", speed);

        // The FOURTH rate factor, and the only one with no other way to reach it.
        // Playback rate is clip.speed x state.speed x THIS x CAnimator::speedMultiplier;
        // the other three are authored on assets or the component, so without a state
        // naming a speed parameter the product is never exercised at full width.
        // `Run` names this one, `Walk Back` deliberately does not -- holding Shift must
        // retime the run and leave the backward walk alone, which is what shows the
        // factor is per STATE rather than per animator.
        //
        // Ramped rather than switched, because the point of a Float parameter is that it
        // varies continuously; a binary would be indistinguishable from a second state.
        // This is also the honest limit of `speedParameter` as the blend-tree stand-in --
        // it is a sped-up run, not a walk->run blend, and it reads fine to about 1.75x.
        const float sprintTarget = IsHeld(NOUS_SCANCODE::LShift) ? m_sprintScale : 1.0f;

        float k = deltaTime * 6.0f;
        if (k > 1.0f) k = 1.0f;              // a frame hitch must not overshoot the ramp
        m_moveSpeed += (sprintTarget - m_moveSpeed) * k;

        Nous_Engine->Animator->SetFloat(m_ownerID, "moveSpeed", m_moveSpeed);

        // A/D yaw the CHARACTER, not the camera. Root motion travels along the
        // character's own facing, so turning him is what steers -- and it is why this
        // lives here rather than in the camera script: the camera observes, the
        // character's own script decides where he faces.
        //
        // Degrees, and scaled by deltaTime so the turn rate does not depend on frame
        // rate. Rotate pre-multiplies in WORLD space, which is what keeps a yaw about
        // world up from drifting into a roll as the character turns.
        float turn = 0.0f;
        if (IsHeld(NOUS_SCANCODE::A)) turn += m_turnSpeed * deltaTime;
        if (IsHeld(NOUS_SCANCODE::D)) turn -= m_turnSpeed * deltaTime;

        if (turn != 0.0f)
            Nous_Engine->GameObject->Rotate(m_ownerID, 0.0f, turn, 0.0f);

        // A trigger stays set until a transition consumes it, so this is set on the
        // key EDGE -- setting it every frame while held would re-arm it the instant
        // the Attack transition consumed it, and the character would never leave.
        if (Nous_Engine->Input->GetKey(NOUS_SCANCODE::Space) == InputAPI::KeyState::DOWN)
            Nous_Engine->Animator->SetTrigger(m_ownerID, "attack");

        // F is the WRONG way to do it, kept on purpose: it re-arms the trigger every
        // frame it is held, which is exactly the input pattern the Any State rule
        // "never re-enter the state already current" exists to survive. Held down, the
        // attack must play through ONCE and reach its exit time -- if it restarts every
        // frame the character freezes on the attack's first pose, which is Unity's
        // classic canTransitionToSelf stutter.
        //
        // Space (the edge) is what a real player controller does, so the rule is
        // unreachable through normal play; this key is what makes it testable without
        // editing a script mid-QA.
        if (IsHeld(NOUS_SCANCODE::F))
            Nous_Engine->Animator->SetTrigger(m_ownerID, "attack");

        // The OVERRIDE, kept beside the parameters on purpose: these win for their
        // frame and the graph resumes from the state they entered on the next one.
        CrossFadeOnKey(NOUS_SCANCODE::Num1, m_stateA);
        CrossFadeOnKey(NOUS_SCANCODE::Num2, m_stateB);
        CrossFadeOnKey(NOUS_SCANCODE::Num3, m_stateC);

        // Once a second, so the log stays readable at 60 fps.
        m_logTimer += deltaTime;
        if (m_logTimer >= 1.0f)
        {
            m_logTimer = 0.0f;

            char state[128] = {};
            Nous_Engine->Animator->GetCurrentState(m_ownerID, state, sizeof(state));
            Nous_Engine->Logger->Info("[AnimatorDemo] state='%s' t=%.2f fading=%d",
                                      state,
                                      Nous_Engine->Animator->GetNormalizedTime(m_ownerID),
                                      Nous_Engine->Animator->IsFading(m_ownerID) ? 1 : 0);
        }
        /*coding_end::AnimatorDemo::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::AnimatorDemo::FixedUpdate*/
        /*coding_end::AnimatorDemo::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::LateUpdate*/
        /*coding_end::AnimatorDemo::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::AnimatorDemo::OnEnable*/
        /*coding_end::AnimatorDemo::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::AnimatorDemo::OnDisable*/
        /*coding_end::AnimatorDemo::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::AnimatorDemo::OnDestroy*/
        /*coding_end::AnimatorDemo::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::AnimatorDemo*/
    // DOWN is the press edge and REPEAT every frame after it, so "held" is both.
    bool IsHeld(NOUS_SCANCODE key) const
    {
        const int state = Nous_Engine->Input->GetKey(key);
        return state == InputAPI::KeyState::DOWN || state == InputAPI::KeyState::REPEAT;
    }

    void CrossFadeOnKey(NOUS_SCANCODE key, const std::string& stateName)
    {
        if (stateName.empty()) return;
        if (Nous_Engine->Input->GetKey(key) != InputAPI::KeyState::DOWN) return;

        // False means the animator has no controller, or its graph has no state by
        // that name -- the most likely mistake here, and silent otherwise, so it is
        // worth logging. A state name is not a clip name: it is whatever the .nctrl
        // calls the state, which is why these are Inspector fields rather than
        // hard-coded strings.
        if (!Nous_Engine->Animator->CrossFade(m_ownerID, stateName.c_str(), m_fade))
            Nous_Engine->Logger->Info("[AnimatorDemo] no state named '%s'", stateName.c_str());
    }
    /*coding_end::AnimatorDemo*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::AnimatorDemo*/
    float m_logTimer = 0.0f;

    // Held across frames because the ramp is relative to where it already was. Starts
    // at the controller's declared default for `moveSpeed`, so the first frame does not
    // lurch before the ramp has run.
    float m_moveSpeed = 1.0f;

    SCRIPT_FIELD(float, m_fade, 0.3f)

    // What Shift ramps `moveSpeed` up to. Exposed rather than hard-coded so the upper
    // end of the usable range can be found by dragging during QA.
    SCRIPT_FIELD(float, m_sprintScale, 1.75f)

    // Degrees per second. Independent of the animation's own speed on purpose: how
    // fast a character pivots is a control feel, not a property of the walk clip.
    SCRIPT_FIELD(float, m_turnSpeed, 140.0f)

    // Defaulted to the names the demo controller uses (Task 16), so the script does
    // something the moment it is dropped on a character that has one.
    SCRIPT_FIELD(std::string, m_stateA, "Idle")
    SCRIPT_FIELD(std::string, m_stateB, "Run")
    SCRIPT_FIELD(std::string, m_stateC, "Attack")
    /*coding_end::AnimatorDemo*/
};

REGISTER_SCRIPT(AnimatorDemo)
