/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::AnimatorDemo*/
/*coding_end::AnimatorDemo*/

// Drives the owning GameObject's CAnimator from script, which is the whole point of
// the animation scripting API: before it, only the Inspector's Play buttons could
// trigger a transition, so no shipped game could animate anything.
//
// Keys 1/2/3 cross-fade to the first three clips in the animator's list.
class AnimatorDemo : public IScript
{
public:

    AnimatorDemo()
    {
        /*coding_start::AnimatorDemo::AnimatorDemo*/
        /*coding_end::AnimatorDemo::AnimatorDemo*/
    }

    ~AnimatorDemo() override
    {
        /*coding_start::AnimatorDemo::~AnimatorDemo*/
        /*coding_end::AnimatorDemo::~AnimatorDemo*/
    }

    void Awake() override
    {
        /*coding_start::AnimatorDemo::Awake*/
        /*coding_end::AnimatorDemo::Awake*/
    }

    void Start() override
    {
        /*coding_start::AnimatorDemo::Start*/
        if (!Nous_Engine->Component->HasAnimator(m_ownerID))
        {
            Nous_Engine->Logger->Info("[AnimatorDemo] No CAnimator on owner %u", m_ownerID);
            return;
        }

        // Round-trips a parameter so the blackboard is exercised even though nothing
        // consumes it until the controller graph exists.
        Nous_Engine->Animator->SetFloat(m_ownerID, "speed", 1.0f);
        Nous_Engine->Logger->Info("[AnimatorDemo] speed parameter reads back as %.2f",
                                  Nous_Engine->Animator->GetFloat(m_ownerID, "speed"));
        /*coding_end::AnimatorDemo::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::Update*/
        PlayOnKey(NOUS_SCANCODE::Num1, m_clipA);
        PlayOnKey(NOUS_SCANCODE::Num2, m_clipB);
        PlayOnKey(NOUS_SCANCODE::Num3, m_clipC);

        // Once a second, so the log stays readable at 60 fps.
        m_logTimer += deltaTime;
        if (m_logTimer >= 1.0f)
        {
            m_logTimer = 0.0f;

            char clip[128] = {};
            Nous_Engine->Animator->GetCurrentClip(m_ownerID, clip, sizeof(clip));
            Nous_Engine->Logger->Info("[AnimatorDemo] clip='%s' t=%.2f fading=%d",
                                      clip,
                                      Nous_Engine->Animator->GetNormalizedTime(m_ownerID),
                                      Nous_Engine->Animator->IsFading(m_ownerID) ? 1 : 0);
        }
        /*coding_end::AnimatorDemo::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::AnimatorDemo::FixedUpdate*/
        /*coding_end::AnimatorDemo::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::AnimatorDemo::LateUpdate*/
        /*coding_end::AnimatorDemo::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::AnimatorDemo::OnEnable*/
        /*coding_end::AnimatorDemo::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::AnimatorDemo::OnDisable*/
        /*coding_end::AnimatorDemo::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::AnimatorDemo::OnDestroy*/
        /*coding_end::AnimatorDemo::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::AnimatorDemo*/
    void PlayOnKey(NOUS_SCANCODE key, const std::string& clipName)
    {
        if (clipName.empty()) return;
        if (Nous_Engine->Input->GetKey(key) != InputAPI::KeyState::DOWN) return;

        // False means no clip in the animator's list has that RESOURCE name -- the
        // most likely mistake here, so it is worth logging rather than ignoring.
        if (!Nous_Engine->Animator->Play(m_ownerID, clipName.c_str(), m_fade))
            Nous_Engine->Logger->Info("[AnimatorDemo] no clip named '%s'", clipName.c_str());
    }
    /*coding_end::AnimatorDemo*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::AnimatorDemo*/
    float m_logTimer = 0.0f;

    SCRIPT_FIELD(float, m_fade, 0.3f)
    SCRIPT_FIELD(std::string, m_clipA, "")
    SCRIPT_FIELD(std::string, m_clipB, "")
    SCRIPT_FIELD(std::string, m_clipC, "")
    /*coding_end::AnimatorDemo*/
};

REGISTER_SCRIPT(AnimatorDemo)
