/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::BounceZ*/
#include <math.h>
/*coding_end::BounceZ*/

// Ping-pongs the owning GameObject along the Z axis around its starting position.
// Sine wave provides built-in ease-in/out at the peaks.
class BounceZ : public IScript
{
public:

    BounceZ()
    {
        /*coding_start::BounceZ::BounceZ*/
        /*coding_end::BounceZ::BounceZ*/
    }

    ~BounceZ() override
    {
        /*coding_start::BounceZ::~BounceZ*/
        /*coding_end::BounceZ::~BounceZ*/
    }

    void Awake() override
    {
        /*coding_start::BounceZ::Awake*/
        Nous_Engine->Logger->Info("[BounceZ] Awake - owner ID: %u", m_ownerID);
        /*coding_end::BounceZ::Awake*/
    }

    void Start() override
    {
        /*coding_start::BounceZ::Start*/
        Nous_Engine->GameObject->GetPosition(m_ownerID, &m_originX, &m_originY, &m_originZ);
        Nous_Engine->Logger->Info("[BounceZ] Start - origin (%.2f, %.2f, %.2f)",
                                   m_originX, m_originY, m_originZ);
        /*coding_end::BounceZ::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::BounceZ::Update*/
        m_time += deltaTime;

        const float offsetZ = m_interval * sinf(m_speed * m_time);

        Nous_Engine->GameObject->SetPosition(m_ownerID,
                                              m_originX,
                                              m_originY,
                                              m_originZ + offsetZ);
        /*coding_end::BounceZ::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::BounceZ::FixedUpdate*/
        /*coding_end::BounceZ::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::BounceZ::LateUpdate*/
        /*coding_end::BounceZ::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::BounceZ::OnEnable*/
        /*coding_end::BounceZ::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::BounceZ::OnDisable*/
        /*coding_end::BounceZ::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::BounceZ::OnDestroy*/
        Nous_Engine->Logger->Info("[BounceZ] OnDestroy");
        /*coding_end::BounceZ::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::BounceZ*/
    /*coding_end::BounceZ*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::BounceZ*/
    float m_time    = 0.0f;
    float m_originX = 0.0f;
    float m_originY = 0.0f;
    float m_originZ = 0.0f;
    SCRIPT_FIELD(float, m_interval, 50.0f)
    SCRIPT_FIELD(float, m_speed,    1.0f)
    /*coding_end::BounceZ*/

};

REGISTER_SCRIPT(BounceZ)
