/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::CameraMovement*/
/*coding_end::CameraMovement*/

class CameraMovement : public IScript
{
public:

    CameraMovement()
    {
        /*coding_start::CameraMovement::CameraMovement*/
        /*coding_end::CameraMovement::CameraMovement*/
    }

    ~CameraMovement() override
    {
        /*coding_start::CameraMovement::~CameraMovement*/
        /*coding_end::CameraMovement::~CameraMovement*/
    }

    void Awake() override
    {
        /*coding_start::CameraMovement::Awake*/
        /*coding_end::CameraMovement::Awake*/
    }

    void Start() override
    {
        /*coding_start::CameraMovement::Start*/
        /*coding_end::CameraMovement::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::CameraMovement::Update*/
        float fx, fy, fz;
        float rx, ry, rz;
        Nous_Engine->GameObject->GetForward(m_ownerID, &fx, &fy, &fz);
        Nous_Engine->GameObject->GetRight  (m_ownerID, &rx, &ry, &rz);

        float dx = 0.0f, dy = 0.0f, dz = 0.0f;
        const float dist = m_speed * deltaTime;

        if (IsHeld(NOUS_SCANCODE::W)) { dx += fx * dist; dy += fy * dist; dz += fz * dist; }
        if (IsHeld(NOUS_SCANCODE::S)) { dx -= fx * dist; dy -= fy * dist; dz -= fz * dist; }
        if (IsHeld(NOUS_SCANCODE::D)) { dx += rx * dist; dy += ry * dist; dz += rz * dist; }
        if (IsHeld(NOUS_SCANCODE::A)) { dx -= rx * dist; dy -= ry * dist; dz -= rz * dist; }

        if (dx != 0.0f || dy != 0.0f || dz != 0.0f)
            Nous_Engine->GameObject->Translate(m_ownerID, dx, dy, dz);
        /*coding_end::CameraMovement::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::CameraMovement::FixedUpdate*/
        /*coding_end::CameraMovement::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::CameraMovement::LateUpdate*/
        /*coding_end::CameraMovement::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::CameraMovement::OnEnable*/
        /*coding_end::CameraMovement::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::CameraMovement::OnDisable*/
        /*coding_end::CameraMovement::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::CameraMovement::OnDestroy*/
        /*coding_end::CameraMovement::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::CameraMovement*/
    bool IsHeld(NOUS_SCANCODE key)
    {
        int state = Nous_Engine->Input->GetKey(key);
        return state == InputAPI::KeyState::DOWN || state == InputAPI::KeyState::REPEAT;
    }
    /*coding_end::CameraMovement*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::CameraMovement*/
    SCRIPT_FIELD(float, m_speed, 5.0f)
    /*coding_end::CameraMovement*/

};

REGISTER_SCRIPT(CameraMovement)
