/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::HotReloadTest*/
/*coding_end::HotReloadTest*/

class HotReloadTest : public IScript
{
public:

    HotReloadTest()
    {
        /*coding_start::HotReloadTest::HotReloadTest*/
        /*coding_end::HotReloadTest::HotReloadTest*/
    }

    ~HotReloadTest() override
    {
        /*coding_start::HotReloadTest::~HotReloadTest*/
        /*coding_end::HotReloadTest::~HotReloadTest*/
    }

    void Awake() override
    {
        /*coding_start::HotReloadTest::Awake*/
        /*coding_end::HotReloadTest::Awake*/
    }

    void Start() override
    {
        /*coding_start::HotReloadTest::Start*/
        Nous_Engine->Logger->Fatal("[HotReloadTest] Started — version: %.0f", m_version);
        /*coding_end::HotReloadTest::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::HotReloadTest::Update*/
        m_timer += deltaTime;
        if (m_timer >= m_interval)
        {
            m_timer = 0.0f;
            Nous_Engine->Logger->Fatal("[HotReloadTest] version: %.0f", m_version);
        }
        /*coding_end::HotReloadTest::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::HotReloadTest::FixedUpdate*/
        /*coding_end::HotReloadTest::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::HotReloadTest::LateUpdate*/
        /*coding_end::HotReloadTest::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::HotReloadTest::OnEnable*/
        /*coding_end::HotReloadTest::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::HotReloadTest::OnDisable*/
        /*coding_end::HotReloadTest::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::HotReloadTest::OnDestroy*/
        /*coding_end::HotReloadTest::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::HotReloadTest*/
    /*coding_end::HotReloadTest*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::HotReloadTest*/
    float m_version = 31.0f;  // bump this between recompiles to verify hot-reload
    float m_interval = 1.0f;  // seconds between log prints
    /*coding_end::HotReloadTest*/

    float m_timer = 0.0f;

};

REGISTER_SCRIPT(HotReloadTest)


