/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::LightMaterialTest*/
/*coding_end::LightMaterialTest*/

// Attach to a GameObject that has a CLight.
// Set m_targetMaterial to a GameObject with a CMaterial whose shader exposes
// a Vec4 uniform named m_uniformName (default: "albedo").
//
// Controls (in Play mode):
//   L — log current light color and intensity
//   R / G / B — set light color to red / green / blue
//   I / D — increase / decrease light intensity by 1
//   M — apply m_colorR/G/B/A to the target material's uniform

class LightMaterialTest : public IScript
{
public:

    LightMaterialTest()
    {
        /*coding_start::LightMaterialTest::LightMaterialTest*/
        /*coding_end::LightMaterialTest::LightMaterialTest*/
    }

    ~LightMaterialTest() override
    {
        /*coding_start::LightMaterialTest::~LightMaterialTest*/
        /*coding_end::LightMaterialTest::~LightMaterialTest*/
    }

    void Awake() override
    {
        /*coding_start::LightMaterialTest::Awake*/
        /*coding_end::LightMaterialTest::Awake*/
    }

    void Start() override
    {
        /*coding_start::LightMaterialTest::Start*/
        /*coding_end::LightMaterialTest::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::LightMaterialTest::Update*/

        // --- Light controls ---
        if (IsDown(NOUS_SCANCODE::L))
        {
            float r = 0, g = 0, b = 0;
            Nous_Engine->Light->GetColor(m_ownerID, &r, &g, &b);
            const float intensity = Nous_Engine->Light->GetIntensity(m_ownerID);
            Nous_Engine->Logger->Fatal("[Light] color=(%.2f,%.2f,%.2f) intensity=%.2f", r, g, b, intensity);
        }
        if (IsDown(NOUS_SCANCODE::R)) Nous_Engine->Light->SetColor(m_ownerID, 1.0f, 0.0f, 0.0f);
        if (IsDown(NOUS_SCANCODE::G)) Nous_Engine->Light->SetColor(m_ownerID, 0.0f, 1.0f, 0.0f);
        if (IsDown(NOUS_SCANCODE::B)) Nous_Engine->Light->SetColor(m_ownerID, 0.0f, 0.0f, 1.0f);
        if (IsDown(NOUS_SCANCODE::I))
            Nous_Engine->Light->SetIntensity(m_ownerID, Nous_Engine->Light->GetIntensity(m_ownerID) + 1.0f);
        if (IsDown(NOUS_SCANCODE::D))
            Nous_Engine->Light->SetIntensity(m_ownerID, Nous_Engine->Light->GetIntensity(m_ownerID) - 1.0f);

        // --- Material control ---
        if (IsDown(NOUS_SCANCODE::M) && m_targetMaterial != 0)
        {
            Nous_Engine->Material->SetVec4(m_targetMaterial, m_uniformName.c_str(),
                m_colorR, m_colorG, m_colorB, m_colorA);
            Nous_Engine->Logger->Fatal("[Material] set '%s' on GO %u -> (%.2f,%.2f,%.2f,%.2f)",
                m_uniformName.c_str(), m_targetMaterial, m_colorR, m_colorG, m_colorB, m_colorA);
        }

        /*coding_end::LightMaterialTest::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::LightMaterialTest::FixedUpdate*/
        /*coding_end::LightMaterialTest::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::LightMaterialTest::LateUpdate*/
        /*coding_end::LightMaterialTest::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::LightMaterialTest::OnEnable*/
        /*coding_end::LightMaterialTest::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::LightMaterialTest::OnDisable*/
        /*coding_end::LightMaterialTest::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::LightMaterialTest::OnDestroy*/
        /*coding_end::LightMaterialTest::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::LightMaterialTest*/
    bool IsDown(NOUS_SCANCODE key) { return Nous_Engine->Input->GetKey(key) == InputAPI::KeyState::DOWN; }
    /*coding_end::LightMaterialTest*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::LightMaterialTest*/
    SCRIPT_GAMEOBJECT(m_targetMaterial, 0)
    SCRIPT_FIELD(std::string, m_uniformName, "albedo")
    SCRIPT_FIELD(float, m_colorR, 1.0f)
    SCRIPT_FIELD(float, m_colorG, 0.0f)
    SCRIPT_FIELD(float, m_colorB, 0.0f)
    SCRIPT_FIELD(float, m_colorA, 1.0f)
    /*coding_end::LightMaterialTest*/

};

REGISTER_SCRIPT(LightMaterialTest)
