/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::MoveScript*/
/*coding_end::MoveScript*/

// Moves the owning GameObject along the X axis every frame using the scripting API.
class MoveScript : public IScript
{
public:

    MoveScript()
    {
        /*coding_start::MoveScript::MoveScript*/
        /*coding_end::MoveScript::MoveScript*/
    }

    ~MoveScript() override
    {
        /*coding_start::MoveScript::~MoveScript*/
        /*coding_end::MoveScript::~MoveScript*/
    }

    void Awake() override
    {
        /*coding_start::MoveScript::Awake*/
        Nous_Engine->Logger->Info("[MoveScript] Awake — owner ID: %u", m_ownerID);
        /*coding_end::MoveScript::Awake*/
    }

    void Start() override
    {
        /*coding_start::MoveScript::Start*/
        // Snapshot the starting position so we can oscillate around it
        Nous_Engine->GameObject->GetPosition(m_ownerID, &m_originX, &m_originY, &m_originZ);
        Nous_Engine->Logger->Info("[MoveScript] Start — origin (%.2f, %.2f, %.2f)",
                                   m_originX, m_originY, m_originZ);
        /*coding_end::MoveScript::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::MoveScript::Update*/
        m_time += deltaTime;

        // Simple sinusoidal oscillation along the X axis (amplitude 2, period ~6s)
        const float offsetX = m_amplitude * sinf(m_speed * m_time);

        Nous_Engine->GameObject->SetPosition(m_ownerID,
                                              m_originX + offsetX,
                                              m_originY,
                                              m_originZ);
        /*coding_end::MoveScript::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::MoveScript::FixedUpdate*/
        /*coding_end::MoveScript::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::MoveScript::LateUpdate*/
        /*coding_end::MoveScript::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::MoveScript::OnEnable*/
        /*coding_end::MoveScript::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::MoveScript::OnDisable*/
        /*coding_end::MoveScript::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::MoveScript::OnDestroy*/
        Nous_Engine->Logger->Info("[MoveScript] OnDestroy");
        /*coding_end::MoveScript::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::MoveScript*/
    /*coding_end::MoveScript*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::MoveScript*/
    float m_time      = 0.0f;
    float m_originX   = 0.0f;
    float m_originY   = 0.0f;
    float m_originZ   = 0.0f;
    float m_amplitude = 200.0f; // units
    float m_speed     = 1.0f;   // radians/second
    /*coding_end::MoveScript*/

};

REGISTER_SCRIPT(MoveScript)
