/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::MoveScriptGameObject*/
/*coding_end::MoveScriptGameObject*/

// Moves the owning GameObject along the X axis every frame using the scripting API.
class MoveScriptGameObject : public IScript
{
public:

    MoveScriptGameObject()
    {
        /*coding_start::MoveScriptGameObject::MoveScriptGameObject*/
        /*coding_end::MoveScriptGameObject::MoveScriptGameObject*/
    }

    ~MoveScriptGameObject() override
    {
        /*coding_start::MoveScriptGameObject::~MoveScriptGameObject*/
        /*coding_end::MoveScriptGameObject::~MoveScriptGameObject*/
    }

    void Awake() override
    {
        /*coding_start::MoveScriptGameObject::Awake*/
        Nous_Engine->Logger->Info("[MoveScriptGameObject] Awake — owner ID: %u", m_ownerID);
        /*coding_end::MoveScriptGameObject::Awake*/
    }

    void Start() override
    {
        /*coding_start::MoveScriptGameObject::Start*/
        // Snapshot the starting position so we can oscillate around it
        Nous_Engine->GameObject->GetPosition(m_ownerID, &m_originX, &m_originY, &m_originZ);
        Nous_Engine->Logger->Info("[MoveScriptGameObject] Start — origin (%.2f, %.2f, %.2f)",
                                   m_originX, m_originY, m_originZ);
        /*coding_end::MoveScriptGameObject::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::MoveScriptGameObject::Update*/
        m_time += deltaTime;

        // Simple sinusoidal oscillation along the X axis (amplitude 2, period ~6s)
        const float offsetX = m_amplitude * sinf(m_speed * m_time);

        Nous_Engine->GameObject->SetRotation(m_target,
                                              m_originX,
                                              m_originY + offsetX,
                                              m_originZ);
        NOUS_SCRIPT_TRACE("MOVING");
        /*coding_end::MoveScriptGameObject::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::MoveScriptGameObject::FixedUpdate*/
        /*coding_end::MoveScriptGameObject::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::MoveScriptGameObject::LateUpdate*/
        /*coding_end::MoveScriptGameObject::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::MoveScriptGameObject::OnEnable*/
        /*coding_end::MoveScriptGameObject::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::MoveScriptGameObject::OnDisable*/
        /*coding_end::MoveScriptGameObject::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::MoveScriptGameObject::OnDestroy*/
        Nous_Engine->Logger->Info("[MoveScriptGameObject] OnDestroy");
        /*coding_end::MoveScriptGameObject::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::MoveScriptGameObject*/
    /*coding_end::MoveScriptGameObject*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, "Label", defaultValue) to expose a field to the Inspector.
    /*coding_start::MoveScriptGameObject*/
    float m_time    = 0.0f;
    float m_originX = 0.0f;
    float m_originY = 0.0f;
    float m_originZ = 0.0f;
    SCRIPT_FIELD(float, m_amplitude, 200.0f)
    SCRIPT_FIELD(float, m_speed,     1.0f)
    SCRIPT_GAMEOBJECT(m_target, 0);
    /*coding_end::MoveScriptGameObject*/

};

REGISTER_SCRIPT(MoveScriptGameObject)
