/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::NEW_TEST*/
#include <iostream>
/*coding_end::NEW_TEST*/

class NEW_TEST : public IScript
{
public:

    NEW_TEST()
    {
        /*coding_start::NEW_TEST::NEW_TEST*/
        /*coding_end::NEW_TEST::NEW_TEST*/
    }

    ~NEW_TEST() override
    {
        /*coding_start::NEW_TEST::~NEW_TEST*/
        /*coding_end::NEW_TEST::~NEW_TEST*/
    }

    void Awake() override
    {
        /*coding_start::NEW_TEST::Awake*/
        Nous_Engine->Logger->Info("[%s] OMG i canot belive my eyes", __FUNCTION__);
        /*coding_end::NEW_TEST::Awake*/
    }

    void Start() override
    {
        /*coding_start::NEW_TEST::Start*/
        /*coding_end::NEW_TEST::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::NEW_TEST::Update*/
        /*coding_end::NEW_TEST::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::NEW_TEST::FixedUpdate*/
        /*coding_end::NEW_TEST::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::NEW_TEST::LateUpdate*/
        /*coding_end::NEW_TEST::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::NEW_TEST::OnEnable*/
        /*coding_end::NEW_TEST::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::NEW_TEST::OnDisable*/
        /*coding_end::NEW_TEST::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::NEW_TEST::OnDestroy*/
        /*coding_end::NEW_TEST::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::NEW_TEST*/
    /*coding_end::NEW_TEST*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::NEW_TEST*/
    /*coding_end::NEW_TEST*/

};

REGISTER_SCRIPT(NEW_TEST)