/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::OrbitLight*/
#include <math.h>
/*coding_end::OrbitLight*/

// Orbits the owning GameObject around the world origin on the XZ plane.
// Attach to a point light to make it circle around an object placed at the origin.
class OrbitLight : public IScript
{
public:

    OrbitLight()
    {
        /*coding_start::OrbitLight::OrbitLight*/
        /*coding_end::OrbitLight::OrbitLight*/
    }

    ~OrbitLight() override
    {
        /*coding_start::OrbitLight::~OrbitLight*/
        /*coding_end::OrbitLight::~OrbitLight*/
    }

    void Awake() override
    {
        /*coding_start::OrbitLight::Awake*/
        Nous_Engine->Logger->Info("[OrbitLight] Awake - owner ID: %u", m_ownerID);
        /*coding_end::OrbitLight::Awake*/
    }

    void Start() override
    {
        /*coding_start::OrbitLight::Start*/
        // Snapshot the starting Y so we can keep the orbit on a fixed horizontal plane
        float x = 0.0f, z = 0.0f;
        Nous_Engine->GameObject->GetPosition(m_ownerID, &x, &m_originY, &z);
        Nous_Engine->Logger->Info("[OrbitLight] Start - orbiting origin at height %.2f", m_originY);
        /*coding_end::OrbitLight::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::OrbitLight::Update*/
        m_time += deltaTime;

        const float angle = m_speed * m_time;
        const float x = m_radius * cosf(angle);
        const float z = m_radius * sinf(angle);

        Nous_Engine->GameObject->SetPosition(m_ownerID, x, m_originY, z);
        /*coding_end::OrbitLight::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::OrbitLight::FixedUpdate*/
        /*coding_end::OrbitLight::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::OrbitLight::LateUpdate*/
        /*coding_end::OrbitLight::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::OrbitLight::OnEnable*/
        /*coding_end::OrbitLight::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::OrbitLight::OnDisable*/
        /*coding_end::OrbitLight::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::OrbitLight::OnDestroy*/
        Nous_Engine->Logger->Info("[OrbitLight] OnDestroy");
        /*coding_end::OrbitLight::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::OrbitLight*/
    /*coding_end::OrbitLight*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::OrbitLight*/
    float m_time    = 0.0f;
    float m_originY = 20.0f;
    SCRIPT_FIELD(float, m_radius, 5.0f)
    SCRIPT_FIELD(float, m_speed,  1.0f)
    /*coding_end::OrbitLight*/

};

REGISTER_SCRIPT(OrbitLight)

