/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Engine/Scripting/Internal/IScript.inl>
#include <Engine/Scripting/Internal/ScriptRegistry.inl>
#include <Engine/Scripting/EngineAPI/EngineAPI.h>
#include <Engine/Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::PlayerController*/
/*coding_end::PlayerController*/

class PlayerController : public IScript
{
public:

    PlayerController()
    {
        /*coding_start::PlayerController::PlayerController*/
        Nous_Engine->Logger->Debug(__FUNCTION__);
        /*coding_end::PlayerController::PlayerController*/
    }

    ~PlayerController() override
    {
        /*coding_start::PlayerController::~PlayerController*/
        Nous_Engine->Logger->Debug(__FUNCTION__);
        /*coding_end::PlayerController::~PlayerController*/
    }

    void Awake() override
    {
        /*coding_start::PlayerController::Awake*/
        for (int i = 0; i < 5; i++)
        {
            Nous_Engine->Logger->Debug("HOLA!");
        }
        Nous_Engine->Logger->Debug("ADIOS ADIOS ADIOS ADIOS");
        Nous_Engine->Logger->Debug(__FUNCTION__);
        /*coding_end::PlayerController::Awake*/
    }

    void Start() override
    {
        /*coding_start::PlayerController::Start*/
        Nous_Engine->Logger->Debug(__FUNCTION__);
        /*coding_end::PlayerController::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::PlayerController::Update*/
        /*coding_end::PlayerController::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::PlayerController::FixedUpdate*/
        /*coding_end::PlayerController::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::PlayerController::LateUpdate*/
        /*coding_end::PlayerController::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::PlayerController::OnEnable*/
        /*coding_end::PlayerController::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::PlayerController::OnDisable*/
        /*coding_end::PlayerController::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::PlayerController::OnDestroy*/
        /*coding_end::PlayerController::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::PlayerController*/
    /*coding_end::PlayerController*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::PlayerController*/
    /*coding_end::PlayerController*/

};

REGISTER_SCRIPT(PlayerController)