/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::RotateY*/
/*coding_end::RotateY*/

// Continuously rotates the owning GameObject around its Y axis.
// Attach to any object and tweak m_speed in the Inspector.
class RotateY : public IScript
{
public:

    RotateY()
    {
        /*coding_start::RotateY::RotateY*/
        /*coding_end::RotateY::RotateY*/
    }

    ~RotateY() override
    {
        /*coding_start::RotateY::~RotateY*/
        /*coding_end::RotateY::~RotateY*/
    }

    void Awake() override
    {
        /*coding_start::RotateY::Awake*/
        /*coding_end::RotateY::Awake*/
    }

    void Start() override
    {
        /*coding_start::RotateY::Start*/
        /*coding_end::RotateY::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::RotateY::Update*/
        float x = 0.0f, y = 0.0f, z = 0.0f;
        Nous_Engine->GameObject->GetRotation(m_ownerID, &x, &y, &z);
        y += m_speed * deltaTime;
        Nous_Engine->GameObject->SetRotation(m_ownerID, x, y, z);
        /*coding_end::RotateY::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::RotateY::FixedUpdate*/
        /*coding_end::RotateY::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::RotateY::LateUpdate*/
        /*coding_end::RotateY::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::RotateY::OnEnable*/
        /*coding_end::RotateY::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::RotateY::OnDisable*/
        /*coding_end::RotateY::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::RotateY::OnDestroy*/
        /*coding_end::RotateY::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::RotateY*/
    /*coding_end::RotateY*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::RotateY*/
    SCRIPT_FIELD(float, m_speed, 90.0f)  // degrees per second
    /*coding_end::RotateY*/

};

REGISTER_SCRIPT(RotateY)
