/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include "Scripting System/Internal/IScript.inl"
#include "Scripting System/Internal/ScriptRegistry.inl"
#include "Scripting System/Bindings/EngineAPI.h"

// ----- HEADER FILES ----- //
/*coding_start::Rykan*/
/*coding_end::Rykan*/

class Rykan : public IScript
{
public:

    Rykan()
    {
        /*coding_start::Rykan::Rykan*/
        /*coding_end::Rykan::Rykan*/
    }

    ~Rykan() override
    {
        /*coding_start::Rykan::~Rykan*/
        /*coding_end::Rykan::~Rykan*/
    }

    void Awake() override
    {
        /*coding_start::Rykan::Awake*/
        Nous_Engine->Logger.Warn(__FUNCTION__);
        //DoSomething();
        /*coding_end::Rykan::Awake*/
    }

    void Start() override
    {
        /*coding_start::Rykan::Start*/
        //Nous_Engine->GameObject.Destroy(gameobjectHandleID);
        /*coding_end::Rykan::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::Rykan::Update*/
        // Check for F4 key press
        if (Nous_Engine->Input.GetKey(InputAPI::SDL_SCANCODE_F) == InputAPI::KeyState::DOWN)
        {
            Nous_Engine->Logger.Fatal("F key pressed!");
            Nous_Engine->GameObject.Create("HOLAAAA");
        }

        if (Nous_Engine->Input.GetKey(InputAPI::SDL_SCANCODE_H) == InputAPI::KeyState::DOWN)
        {
            Nous_Engine->Logger.Fatal("H key pressed!");
            Nous_Engine->GameObject.Create("RYKAAAAN");
        }
        /*coding_end::Rykan::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::Rykan::FixedUpdate*/
        /*coding_end::Rykan::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::Rykan::LateUpdate*/
        /*coding_end::Rykan::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::Rykan::OnEnable*/
        /*coding_end::Rykan::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::Rykan::OnDisable*/
        /*coding_end::Rykan::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::Rykan::OnDestroy*/
        /*coding_end::Rykan::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::Rykan*/
    void DoSomething()
    {
        Nous_Engine->Logger.Warn("Doing something");
        gameobjectHandleID = Nous_Engine->GameObject.Create("HolaSoyRykan");
        Nous_Engine->Logger.Warn("Created gameobject with ID: %u", gameobjectHandleID);

        Nous_Engine->GameObject.SetPosition(gameobjectHandleID, 69.0f, 69.0f, 69.0f);
        Nous_Engine->GameObject.SetRotation(gameobjectHandleID, 69.0f, 69.0f, 69.0f);
        Nous_Engine->GameObject.SetScale(gameobjectHandleID, 69.0f, 69.0f, 69.0f);
    }
    /*coding_end::Rykan*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::Rykan*/
    uint32_t gameobjectHandleID = 0;
    /*coding_end::Rykan*/

};

REGISTER_SCRIPT(Rykan)