/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::StringFieldTest*/
/*coding_end::StringFieldTest*/

class StringFieldTest : public IScript
{
public:

    StringFieldTest()
    {
        /*coding_start::StringFieldTest::StringFieldTest*/
        /*coding_end::StringFieldTest::StringFieldTest*/
    }

    ~StringFieldTest() override
    {
        /*coding_start::StringFieldTest::~StringFieldTest*/
        /*coding_end::StringFieldTest::~StringFieldTest*/
    }

    void Awake() override
    {
        /*coding_start::StringFieldTest::Awake*/
        /*coding_end::StringFieldTest::Awake*/
    }

    void Start() override
    {
        /*coding_start::StringFieldTest::Start*/
        /*coding_end::StringFieldTest::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::StringFieldTest::Update*/
        const int state = Nous_Engine->Input->GetKey(NOUS_SCANCODE::Return);
        if (state == InputAPI::KeyState::DOWN)
            Nous_Engine->Logger->Fatal("[StringFieldTest] message: '%s'", m_message.c_str());
        /*coding_end::StringFieldTest::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::StringFieldTest::FixedUpdate*/
        /*coding_end::StringFieldTest::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::StringFieldTest::LateUpdate*/
        /*coding_end::StringFieldTest::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::StringFieldTest::OnEnable*/
        /*coding_end::StringFieldTest::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::StringFieldTest::OnDisable*/
        /*coding_end::StringFieldTest::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::StringFieldTest::OnDestroy*/
        /*coding_end::StringFieldTest::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::StringFieldTest*/
    /*coding_end::StringFieldTest*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::StringFieldTest*/
    SCRIPT_FIELD(std::string, m_message, "Hello Nous!")
    /*coding_end::StringFieldTest*/

};

REGISTER_SCRIPT(StringFieldTest)
