/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include "Scripting System/Internal/IScript.inl"
#include "Scripting System/Internal/ScriptRegistry.inl"

// ----- HEADER FILES ----- //
/*coding_start::Test*/
#include <iostream>
/*coding_end::Test*/

class Test : public IScript
{
public:

    Test()
    {
        /*coding_start::Test::Test*/
        /*coding_end::Test::Test*/
    }

    ~Test() override
    {
        /*coding_start::Test::~Test*/
        /*coding_end::Test::~Test*/
    }

    void Awake() override
    {
        /*coding_start::Test::Awake*/
        std::cout << "This is a NOT" << std::endl;
        /*coding_end::Test::Awake*/
    }

    void Start() override
    {
        /*coding_start::Test::Start*/
        /*coding_end::Test::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::Test::Update*/
        /*coding_end::Test::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::Test::FixedUpdate*/
        /*coding_end::Test::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::Test::LateUpdate*/
        /*coding_end::Test::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::Test::OnEnable*/
        /*coding_end::Test::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::Test::OnDisable*/
        /*coding_end::Test::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::Test::OnDestroy*/
        /*coding_end::Test::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::Test*/
    /*coding_end::Test*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::Test*/
    /*coding_end::Test*/

};

REGISTER_SCRIPT(Test)