/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include <Scripting/Internal/IScript.inl>
#include <Scripting/Internal/ScriptRegistry.inl>
#include <Scripting/EngineAPI/EngineAPI.h>
#include <Scripting/EngineAPI/Bindings/ScriptBindings.h>

// ----- HEADER FILES ----- //
/*coding_start::ThirdPersonCamera*/
#include <cmath>   // std::exp, for the frame-rate-independent follow
/*coding_end::ThirdPersonCamera*/

// Orbits this GameObject's camera around a target character.
//
// It only ever moves the CAMERA. The character is moved by root motion -- the
// animation's own travel, applied to its transform -- so a camera that also pushed
// the character would be a second writer of the same position, and the two would
// fight in a way that reads as jitter rather than as a bug.
//
// Hold RIGHT MOUSE to orbit. Deliberately not mouse CAPTURE on Escape, which is what
// the free-fly CameraMovement script does: in the editor Escape is still the quit
// shortcut (it is gated on !gameMode), so the first attempt to release the cursor
// would close EditorApp. Right-drag needs no capture and behaves the same in the
// editor and in a shipped game.
class ThirdPersonCamera : public IScript
{
public:

    ThirdPersonCamera()
    {
        /*coding_start::ThirdPersonCamera::ThirdPersonCamera*/
        /*coding_end::ThirdPersonCamera::ThirdPersonCamera*/
    }

    ~ThirdPersonCamera() override
    {
        /*coding_start::ThirdPersonCamera::~ThirdPersonCamera*/
        /*coding_end::ThirdPersonCamera::~ThirdPersonCamera*/
    }

    void Awake() override
    {
        /*coding_start::ThirdPersonCamera::Awake*/
        /*coding_end::ThirdPersonCamera::Awake*/
    }

    void Start() override
    {
        /*coding_start::ThirdPersonCamera::Start*/
        // Resolved once here rather than every frame: FindByName is a scan, and the
        // target does not change for the life of the script. Re-resolved lazily in
        // Update only while it is still missing, so a target spawned later is picked
        // up without making the common case pay for the search.
        m_targetID = Nous_Engine->GameObject->FindByName(m_targetName.c_str());

        if (m_targetID == 0)
            Nous_Engine->Logger->Info("[ThirdPersonCamera] No GameObject named '%s'",
                                      m_targetName.c_str());

        // Snap on the first frame instead of easing in from wherever the camera was
        // left in the editor -- otherwise pressing Play always opens with a swoop.
        m_hasPosition = false;
        /*coding_end::ThirdPersonCamera::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::ThirdPersonCamera::Update*/
        if (m_targetID == 0)
        {
            m_targetID = Nous_Engine->GameObject->FindByName(m_targetName.c_str());
            if (m_targetID == 0) return;
        }

        // ----- Orbit, while the right button is held -----
        if (Nous_Engine->Input->GetMouseButton(3) != InputAPI::KeyState::IDLE)
        {
            int mdx = 0, mdy = 0;
            Nous_Engine->Input->GetMouseMotion(&mdx, &mdy);

            // Same sign convention as CameraMovement: SetRotation builds
            // q_Y(yaw) * q_X(pitch), so both are SUBTRACTED to get mouse-right ->
            // look right and mouse-down -> look down.
            m_yaw   -= static_cast<float>(mdx) * m_sensitivity;
            m_pitch -= static_cast<float>(mdy) * m_sensitivity;

            // Clamped well short of vertical. At +-90 the look direction becomes
            // parallel to the world up the orbit offset is built from, and the camera
            // spins on its own axis at the pole.
            if (m_pitch >  m_maxPitch) m_pitch =  m_maxPitch;
            if (m_pitch < -m_maxPitch) m_pitch = -m_maxPitch;
        }

        // ----- Aim first, then place the camera along its own back vector -----
        //
        // Orienting BEFORE positioning is what makes "always looks at the target"
        // true by construction rather than by a separate look-at: the camera is put
        // exactly `distance` behind the pivot along its own forward, so the vector
        // from camera to pivot IS that forward. A look-at computed after a move can
        // disagree with the move by a frame; this cannot.
        Nous_Engine->GameObject->SetRotation(m_ownerID, m_pitch, m_yaw, 0.0f);

        float fx = 0.0f, fy = 0.0f, fz = 0.0f;
        Nous_Engine->GameObject->GetForward(m_ownerID, &fx, &fy, &fz);

        float tx = 0.0f, ty = 0.0f, tz = 0.0f;
        Nous_Engine->GameObject->GetPosition(m_targetID, &tx, &ty, &tz);

        // The pivot is raised to roughly chest height so the character sits in the
        // frame rather than at the very bottom of it. In the character's own units --
        // a Mixamo rig is authored in centimetres, so this is scaled with it.
        const float px = tx;
        const float py = ty + m_height;
        const float pz = tz;

        const float dx = px - fx * m_distance;
        const float dy = py - fy * m_distance;
        const float dz = pz - fz * m_distance;

        // ----- Smoothed follow -----
        //
        // Frame-rate independent: the naive `current += (desired - current) * k`
        // converges faster at higher frame rates, so the camera feels different on a
        // 60 Hz and a 144 Hz machine. The exponential form fixes the time constant.
        if (!m_hasPosition)
        {
            m_camX = dx; m_camY = dy; m_camZ = dz;
            m_hasPosition = true;
        }
        else
        {
            const float t = 1.0f - std::exp(-m_smoothing * deltaTime);
            m_camX += (dx - m_camX) * t;
            m_camY += (dy - m_camY) * t;
            m_camZ += (dz - m_camZ) * t;
        }

        Nous_Engine->GameObject->SetPosition(m_ownerID, m_camX, m_camY, m_camZ);
        /*coding_end::ThirdPersonCamera::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::ThirdPersonCamera::FixedUpdate*/
        /*coding_end::ThirdPersonCamera::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::ThirdPersonCamera::LateUpdate*/
        /*coding_end::ThirdPersonCamera::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::ThirdPersonCamera::OnEnable*/
        /*coding_end::ThirdPersonCamera::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::ThirdPersonCamera::OnDisable*/
        /*coding_end::ThirdPersonCamera::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::ThirdPersonCamera::OnDestroy*/
        /*coding_end::ThirdPersonCamera::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::ThirdPersonCamera*/
    /*coding_end::ThirdPersonCamera*/

private:

    // ----- ATTRIBUTES ----- //
    // Use SCRIPT_FIELD(Type, name, defaultValue) to expose a field to the Inspector.
    /*coding_start::ThirdPersonCamera*/

    // Distance and height are in the CHARACTER's units. A Mixamo rig is authored in
    // centimetres (hips at y ~= 104), so these defaults are sized for that -- on a
    // metres-authored model they want to be ~100x smaller. The same
    // centimetres-versus-metres trap that forces the skeleton debug draw to derive
    // its sizes from the rig.
    SCRIPT_FIELD(std::string, m_targetName, "Cypher Walking")
    SCRIPT_FIELD(float, m_distance,    300.0f)
    SCRIPT_FIELD(float, m_height,      140.0f)
    SCRIPT_FIELD(float, m_sensitivity,   0.25f)
    SCRIPT_FIELD(float, m_maxPitch,     70.0f)

    // Larger converges faster. As a time constant: the camera closes ~63% of the gap
    // in 1/m_smoothing seconds.
    SCRIPT_FIELD(float, m_smoothing,     8.0f)

    uint32_t m_targetID = 0;

    float m_yaw   = 0.0f;
    float m_pitch = -10.0f;   // looking slightly down, the usual third-person framing

    // The smoothed position, kept here rather than read back from the transform each
    // frame: reading it back would fold in anything else that moved the camera, and
    // make the filter chase its own output.
    bool  m_hasPosition = false;
    float m_camX = 0.0f;
    float m_camY = 0.0f;
    float m_camZ = 0.0f;
    /*coding_end::ThirdPersonCamera*/
};

REGISTER_SCRIPT(ThirdPersonCamera)
