/****************************************************
 *  Nous Engine - Script Template v0.1
 *  Auto-generated by Script Generator
 *
 *  Do not edit this header manually.
 *  Only add your logic between the markers:
 *     coding_start and coding_end
 ****************************************************/

#include "Scripting System/Internal/IScript.inl"
#include "Scripting System/Internal/ScriptRegistry.inl"
#include "Scripting System/EngineAPI/EngineAPI.h"
#include "Scripting System/EngineAPI/ScriptBindings.h"

// ----- HEADER FILES ----- //
/*coding_start::$CLASSNAME$*/
/*coding_end::$CLASSNAME$*/

class $CLASSNAME$ : public IScript
{
public:

    $CLASSNAME$()
    {
        /*coding_start::$CLASSNAME$::$CLASSNAME$*/
        /*coding_end::$CLASSNAME$::$CLASSNAME$*/
    }

    ~$CLASSNAME$() override
    {
        /*coding_start::$CLASSNAME$::~$CLASSNAME$*/
        /*coding_end::$CLASSNAME$::~$CLASSNAME$*/
    }

    void Awake() override
    {
        /*coding_start::$CLASSNAME$::Awake*/
        /*coding_end::$CLASSNAME$::Awake*/
    }

    void Start() override
    {
        /*coding_start::$CLASSNAME$::Start*/
        /*coding_end::$CLASSNAME$::Start*/
    }

    void Update(float deltaTime) override
    {
        /*coding_start::$CLASSNAME$::Update*/
        /*coding_end::$CLASSNAME$::Update*/
    }

    void FixedUpdate(float fixedDeltaTime) override
    {
        /*coding_start::$CLASSNAME$::FixedUpdate*/
        /*coding_end::$CLASSNAME$::FixedUpdate*/
    }

    void LateUpdate(float deltaTime) override
    {
        /*coding_start::$CLASSNAME$::LateUpdate*/
        /*coding_end::$CLASSNAME$::LateUpdate*/
    }

    void OnEnable() override
    {
        /*coding_start::$CLASSNAME$::OnEnable*/
        /*coding_end::$CLASSNAME$::OnEnable*/
    }

    void OnDisable() override
    {
        /*coding_start::$CLASSNAME$::OnDisable*/
        /*coding_end::$CLASSNAME$::OnDisable*/
    }

    void OnDestroy() override
    {
        /*coding_start::$CLASSNAME$::OnDestroy*/
        /*coding_end::$CLASSNAME$::OnDestroy*/
    }

    // ----- METHODS ----- //
    /*coding_start::$CLASSNAME$*/
    /*coding_end::$CLASSNAME$*/

private:

    // ----- ATTRIBUTES ----- //
    /*coding_start::$CLASSNAME$*/
    /*coding_end::$CLASSNAME$*/

};

REGISTER_SCRIPT($CLASSNAME$)