add_subdirectory(CAnimator)
add_subdirectory(CCamera)
add_subdirectory(CLight)
add_subdirectory(CMaterial)
add_subdirectory(CMesh)
add_subdirectory(CPrefab)
add_subdirectory(CScript)
add_subdirectory(CTransform)
add_subdirectory(CAudioSource)
add_subdirectory(CAudioListener)
add_subdirectory(CVideoPlayer)